-- CREATE TABLE afootball_phy();

-- -- I wanted to "COPY... WITH... FORMAT" but was unable to access my CSV files' Folder
-- -- So, I imported in the CSV file
-- -- "price" = Price of the Product (1 base unit)

-- ALTER TABLE afootball_phy
-- ADD COLUMN product_name VARCHAR(70),
-- ADD COLUMN brand VARCHAR(60),
-- ADD COLUMN category VARCHAR(50),
-- ADD COLUMN subcategory VARCHAR(50),
-- ADD COLUMN supplier VARCHAR(50),
-- ADD COLUMN dates VARCHAR(60),
-- ADD COLUMN price FLOAT,
-- ADD COLUMN quantity_sold INTEGER,
-- ADD COLUMN amount_sold NUMERIC(10, 2),
-- ADD COLUMN cost_amount NUMERIC(10, 2),
-- ADD COLUMN payment_method VARCHAR(50),
-- ADD COLUMN customer_firstname CHAR(40),
-- ADD COLUMN customer_lastname CHAR(60),
-- ADD COLUMN customer_gender CHAR(15),
-- ADD COLUMN customer_email VARCHAR(60),
-- ADD COLUMN customer_phone VARCHAR(50),
-- ADD COLUMN store_type VARCHAR(50),
-- ADD COLUMN store_street VARCHAR(60),
-- ADD COLUMN store_city VARCHAR(60),
-- ADD COLUMN store_state VARCHAR(2);

-- SELECT * FROM afootball_phy;

-- CREATE TABLE afootball_onl(
-- 	timestamp VARCHAR(60),
-- 	product_category VARCHAR(60),
-- 	product_subcategory VARCHAR(60),
-- 	product VARCHAR(70),
-- 	brand_name VARCHAR(60),
-- 	price FLOAT,
-- 	quantity_sold INTEGER,
-- 	total_amount NUMERIC(10, 2),
-- 	total_costs NUMERIC(10, 2),
-- 	payment_type VARCHAR(50),
-- 	shipping_method VARCHAR(50),
-- 	coupon_discount INTEGER,
-- 	customer_firstname CHAR(50),
-- 	customer_lastname CHAR(70),
-- 	customer_gender VARCHAR(15),
-- 	customer_age INTEGER,
-- 	customer_shirtsize VARCHAR(20),
-- 	customer_email VARCHAR(70),
-- 	customer_phone VARCHAR(50),
-- 	customer_address VARCHAR(70),
-- 	address_details VARCHAR(60),
-- 	customer_city VARCHAR(55),
-- 	customer_state VARCHAR(2),
-- 	store_website VARCHAR(60),
-- 	employee_firstname CHAR(50),
-- 	employee_lastname CHAR(70),
-- 	employee_email VARCHAR(70),
-- 	employee_skill VARCHAR(70),
-- 	employee_education VARCHAR(90)
-- );

SELECT * FROM afootball_onl;

-- EXPLAIN ANALYZE
SELECT * FROM afootball_phy
LIMIT 10;

SELECT product_name AS "Item", SUM(quantity_sold) AS "Total Sold"
FROM afootball_phy
GROUP BY product_name
ORDER BY "Total Sold" DESC LIMIT 10;

-- Which Payment Method do people Spend most with? Debit Card? Cash? Credit Card?
SELECT payment_type AS "Payment Method", SUM(quantity_sold) AS "Total Bought Items",
	   SUM(total_amount) AS "Total Money Spent"
FROM afootball_onl o
JOIN afootball_phy p ON o.payment_type = p.payment_method
GROUP BY payment_type
ORDER BY SUM(total_amount) DESC;

-- JOINing both Tables for Calculations

-- Top 10 Most-Sold (Measured in Revenue Generated by Sales) Items by Brand - In-Person & Online Sales combined
SELECT brand AS "Brand", product_name AS "Item", 
	   SUM(amount_sold) AS "Total Amount Earned - In-Person & Online"
FROM (SELECT *
FROM afootball_phy p
JOIN afootball_onl o ON p.product_name = o.product)
GROUP BY "Brand", "Item"
ORDER BY "Total Amount Earned - In-Person & Online" DESC
LIMIT 10;

-- Common Table Expressions (CTEs)

-- Items Sold Online and in-Person, both, with their Total Revenues Generated and Costs, and Ranked by Net Profit/Loss in Order of Decreasing Net Revenue Earned
WITH subq1 AS (
	SELECT product_name AS "In-Person Product", 
		SUM(quantity_sold) AS "Total Amount of Item Sold", ROUND(SUM(amount_sold), 0) AS "Total Revenue Earned on Item", 
		ROUND(SUM(cost_amount), 0) AS "Total Cost of Item",
		ROUND(SUM(amount_sold) - SUM(cost_amount), 0) AS "Net Return on Item - In-Person"
	FROM afootball_phy
	GROUP BY "In-Person Product"
	ORDER BY "Net Return on Item - In-Person" DESC
),
	 subq2 AS (
	SELECT product AS "Online Product", 
		SUM(quantity_sold) AS "Total Amount of Item Sold", ROUND(SUM(total_amount), 0) AS "Total Revenue Earned on Item", 
		ROUND(SUM(total_costs), 0) AS "Total Cost of Item",
		ROUND(SUM(total_amount) - SUM(total_costs), 0) AS "Net Return on Item - Online"
	FROM afootball_onl
	GROUP BY "Online Product"
	ORDER BY "Net Return on Item - Online" DESC
	 )
SELECT *
FROM subq1
JOIN subq2 ON subq1."In-Person Product" = subq2."Online Product";

-- Let's Clean and Display all Customer Emails who Purchased in-person and online, both
WITH email1 AS (
	SELECT DISTINCT(TRIM(LOWER(customer_email))) AS online_customer_email
	FROM afootball_onl),
	 email2 AS (
	SELECT DISTINCT(TRIM(LOWER(customer_email))) AS inperson_customer_email
	FROM afootball_phy)
SELECT *
FROM email1
JOIN email2 ON email1.online_customer_email = email2.inperson_customer_email;

-- Subqueries:

-- Items whose in-person Average Revenue per Sale is >= their Online one
SELECT 
    b.product_name AS "Item", 
    b.category AS "Category", 
    b.subcategory AS "Subcategory"
FROM 
    afootball_phy b
WHERE 
    (SELECT AVG(b2.amount_sold)
        FROM afootball_phy b2
        WHERE b2.product_name = b.product_name) 
		>= (SELECT AVG(o.total_amount)
        FROM afootball_onl o
        WHERE o.product = b.product_name);


-- Analytical Calculations & WINDOW Functions:

SELECT DISTINCT(product_name) AS "Item", ROUND((amount_sold/cost_amount), 2) AS "RTC Ratio", ROUND((amount_sold - cost_amount), 1) AS "Net RTC Amount"
FROM afootball_phy
GROUP BY "Item", amount_sold, cost_amount
HAVING amount_sold IS NOT NULL
ORDER BY "RTC Ratio" DESC;

SELECT ROUND(CORR((amount_sold/cost_amount), quantity_sold)::numeric, 3) AS "RTC Ratio to Quantity Sold",
	   ROUND(CORR((amount_sold - cost_amount), quantity_sold)::numeric, 3) AS "Net RTC Amount to Quantity Sold"
FROM afootball_phy;

-- Using Percentiles to get Categorical Values for Amounts of Items per Sale
SELECT
	PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY quantity_sold) AS q1, -- <= 3 should be a Small Amount of Items sold
	PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY quantity_sold) AS median_qsold, -- <= 6 should be a Medium Amount
	PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY quantity_sold) AS q3 -- >6: Big Amount of Items sold
FROM afootball_phy;

-- ! Updating the Table with a Categorical Classifier column for the Quantity of Items sold in a Purchase
ALTER TABLE afootball_phy ADD COLUMN amount_sold_category VARCHAR(50);

UPDATE afootball_phy
SET amount_sold_category = CASE
		WHEN quantity_sold <= 3 THEN 'Low Count Sale'
		WHEN quantity_sold <= 6 THEN 'Mid Count Sale'
		WHEN quantity_sold > 6 THEN 'Big Sale'
	ELSE NULL
END;

ALTER TABLE afootball_onl ADD COLUMN amount_sold_category VARCHAR(50);

UPDATE afootball_onl
SET amount_sold_category = CASE
		WHEN quantity_sold <= 3 THEN 'Low Count Sale'
		WHEN quantity_sold <= 6 THEN 'Mid Count Sale'
		WHEN quantity_sold > 6 THEN 'Big Sale'
	ELSE NULL
END;

-- Count of all Sales in each Type of Sale Count Category, for In-person as well as Online Sales
SELECT 
    combined.online_amount_sold_category AS online_amount_sold_category, 
    COUNT(DISTINCT combined.online_amount_sold_category) AS online_sales_total_count,
    combined.inperson_amount_sold_category AS inperson_amount_sold_category, 
    COUNT(DISTINCT combined.inperson_amount_sold_category) AS inperson_sales_total_count
FROM (
    SELECT 
        o.amount_sold_category AS online_amount_sold_category,
        p.amount_sold_category AS inperson_amount_sold_category
    FROM afootball_onl o
    JOIN afootball_phy p ON o.product = p.product_name
) AS combined
GROUP BY combined.online_amount_sold_category, combined.inperson_amount_sold_category;

-- Dividing Item Categories' Total Revenues Earned into Quartile Ranks (1st-25th Percentile in Total Reveue = 1, etc.)
SELECT DISTINCT(category) AS "Category", SUM(amount_sold) AS "Total Revenue",
	   NTILE(4) OVER (ORDER BY SUM(amount_sold)) AS "Quartile Rank"
FROM afootball_phy
GROUP BY category;

-- 90th Percentile Value of an In-Person Sale's "Revenue Generated minus Cost of Item" (Net RTC Amount)
SELECT PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY (amount_sold-cost_amount)) AS "90th Percentile: Net RTC Amount"
FROM afootball_phy;

-- The 10th Percentile Values for Net RTC Amounts by each Quantity of Item Purchase
SELECT quantity_sold AS "Quantity of Items Sold", 
	ROUND(PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY (amount_sold-cost_amount))::NUMERIC, 2) AS "10th Percentile: Net RTC Amount"
FROM afootball_phy
GROUP BY quantity_sold;
-- Looking at the Results, we can Deduce: Ideally, for each Item Quantity purchased in-person, the Seller must try to make an RTC Profit of at least that listed in the 10th Percentile Value column, to keep a 10% Profit

-- WINDOW Function for Analysis

-- "Riddell SPEEDFLEX DIAMOND Helmets" has been the Highest-Grossing Item Overall
-- Let's see how its Total Revenue purchased changes with Customer Age groups
SELECT DISTINCT(customer_age), product, SUM(total_amount),
	(SUM(total_amount) - LAG(SUM(total_amount)) OVER (PARTITION BY product ORDER BY customer_age)) AS diff_previous_yr_total_exp
FROM afootball_onl
WHERE product = 'Riddell SPEEDFLEX DIAMOND Helmets'
GROUP BY customer_age, product;